apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-website
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - secretName: main-website-tls
    hosts:
      - "societatea-hermes.ro"
      - "www.societatea-hermes.ro"
  rules:
  - host: "societatea-hermes.ro"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: main-website
              port:
                number: 80
  - host: "www.societatea-hermes.ro"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: main-website
              port:
                number: 80