apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "false"
  url: https://argocd.societatea-hermes.ro
  application.instanceLabelKey: societatea-hermes.ro/name
  dex.config: |
    connectors:
      - config:
          redirectURI: https://argocd.societatea-hermes.ro/api/dex/callback
          serviceAccountFilePath: /tmp/oidc/googleAuth.json
          adminEmail: admin@societatea-hermes.ro
          clientID: $argocd-oidc:CLIENT_ID
          clientSecret: $argocd-oidc:CLIENT_SECRET
          issuer: https://accounts.google.com
        type: oidc
        id: google
        name: Google