apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: volunteer-management-api
  name: volunteer-management-api
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: volunteer-management-api