apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: volunteer-management-frontend
  name: volunteer-management-frontend
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 5173
  selector:
    app.kubernetes.io/name: volunteer-management-frontend