apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: volunteer-management
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: "https://auth.societatea-hermes.ro/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.societatea-hermes.ro/oauth2/start?rd=https://$host$request_uri"
spec:
  ingressClassName: nginx
  tls:
  - secretName: volunteer-management-tls
    hosts:
      - "volunteers.societatea-hermes.ro"
  rules:
  - host: "volunteers.societatea-hermes.ro"
    http:
      paths:
        - path: /api/v1
          pathType: ImplementationSpecific
          backend:
            service:
              name: volunteer-management-api
              port:
                number: 80
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: volunteer-management-frontend
              port:
                number: 80