apiVersion: v1
kind: ConfigMap
metadata:
  name: ddns-config
data:
  ddclient.conf: |
    daemon=600
    syslog=yes
    pid=/var/run/ddclient/ddclient.pid
    use=web, web=ipinfo.io/ip

    protocol=cloudflare
    zone=societatea-hermes.ro
    login_env=EMAIL
    password_env=API_KEY
    societatea-hermes.ro