apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  scopes: '[groups, email]'
  policy.csv: |
    g, sa@societatea-hermes.ro, role:admin
    g, admin@societatea-hermes.ro, role:admin
    g, developers@societatea-hermes.ro, role:readonly