apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:Societatea-Hermes/hermes-on-kubernetes-secrets.git
      name: hermes-on-kubernetes-secrets
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: github-ssh-key
      type: git
  application.instanceLabelKey: societatea-hermes.ro/name