apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.societatea-hermes.ro
  repositories: |
    - url: git@github.com:Societatea-Hermes/hermes-on-kubernetes-secrets.git
      name: hermes-on-kubernetes-secrets
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: github-ssh-key
      type: git
  application.instanceLabelKey: societatea-hermes.ro/name
  dex.config: |
    connectors:
      - config:
          redirectURI: https://argocd.societatea-hermes.ro/api/dex/callback
          serviceAccountFilePath: /tmp/oidc/googleAuth.json
          adminEmail: admin@societatea-hermes.ro
          clientID: $argocd-oidc:CLIENT_ID
          clientSecret: $argocd-oidc:CLIENT_SECRET
        type: oidc
        id: google
        name: Google