apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: infra
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 1
  upgrade:
    remediation:
      retries: 1
      strategy: rollback 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: apps
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 1
  upgrade:
    remediation:
      retries: 1
      strategy: rollback 
  dependsOn:
    - name: infra