apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    monitoring: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    monitoring: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    monitoring: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    monitoring: prometheus
---
