apiVersion: v1
kind: Service
metadata:
  namespace: apps
  labels:
    app.kubernetes.io/name: main-website
  name: main-website
spec:
  ports:
    - port: 80
      name: 
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: main-website