apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  secretName: oauth2-proxy-tls
  renewBefore: 360h0m0s
  dnsNames:
    - auth.societateahermes.ro
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  revisionHistoryLimit: 2