apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    app.kubernetes.io/name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oauth2-proxy
    spec:
      containers:
        - args:
          - --provider=google
          - --cookie-domain=societatea-hermes.ro
          - --email-domain=societatea-hermes.ro
          - --http-address=0.0.0.0:4180
          - --oidc-issuer-url=https://accounts.google.com
          - --whitelist-domain=.societatea-hermes.ro
          - --skip-provider-button=true
          - --upstream=file:///dev/null
          - --session-cookie-minimal=true
          - --reverse-proxy=true
          - --google-service-account-json=/var/secrets/hermes-bot-sa-key.json
          - --google-admin-email=admin@societatea-hermes.ro
          - --google-group=all@societatea-hermes.ro
          - --google-group=sa@societatea-hermes.ro
          - --google-group=developers@societatea-hermes.ro
          name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
          imagePullPolicy: Always
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: CLIENT_ID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: CLIENT_SECRET
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: COOKIE_SECRET
          ports:
            - containerPort: 4180
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/secrets/"
              name: oauth2-proxy
              readOnly: true
      volumes:
        - name: oauth2-proxy
          secret:
            secretName: oauth2-proxy