apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  ingressClassName: nginx
  tls:
    - secretName: oauth2-proxy-tls
  rules:
    - host: auth.societatea-hermes.ro
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 4180