apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  secretName: argocd-server-tls
  renewBefore: 360h0m0s
  dnsNames:
    - argocd.societatea-hermes.ro
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  revisionHistoryLimit: 2