apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ui
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
    - secretName: argocd-server-tls
  ingressClassName: nginx
  rules:
  - host: argocd.societatea-hermes.ro
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: argocd-server
            port:
              name: https
