apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssmi-certificate
  namespace: apps
spec:
  secretName: tls-ssmi
  renewBefore: 360h0m0s # 15d
  dnsNames:
  - "ssmi.societatea-hermes.ro"
  - "ssmi.societateahermes.ro"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer