apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus
  namespace: monitoring
spec:
  secretName: prometheus-tls
  renewBefore: 360h0m0s
  dnsNames:
    - prometheus.societatea-hermes.ro
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  revisionHistoryLimit: 2
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  secretName: alertmanager-tls
  renewBefore: 360h0m0s
  dnsNames:
    - alertmanager.societatea-hermes.ro
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  revisionHistoryLimit: 2
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretName: grafana-tls
  renewBefore: 360h0m0s
  dnsNames:
    - grafana.societatea-hermes.ro
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  revisionHistoryLimit: 2