apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackathon-ingress
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - secretName: tls-hackathon
    hosts:
      - "hackathon.societateahermes.ro"
      - "hackathon.societatea-hermes.ro"
      - "hackathon.toliveistolearn.com"
  rules:
  # - host: "hackathon.toliveistolearn.com"
  #   http:
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  #         backend:
  #           service:
  #             name: old-hackathon-website
  #             port:
  #               number: 8000
  # - host: "hackathon.societatea-hermes.ro"
  #   http:
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  #         backend:
  #           service:
  #             name: old-hackathon-website
  #             port:
  #               number: 8000
  - host: "hackathon.societateahermes.ro"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: old-hackathon-website
              port:
                number: 8000
  
