{{- if .Values.certManager.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: cert-manager
      version: v1.13.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  targetNamespace: cert-manager
  install:
    remediation:
      retries: 1
  upgrade:
    remediation:
      retries: 1
      strategy: rollback 
# values.yaml
  values:
    installCRDs: true
{{- end }}