{{- if .Values.monitoring.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 51.0.3
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
      reconcileStrategy: Revision
  targetNamespace: monitoring
  upgrade:
    remediation:
      retries: 1
      strategy: rollback 
  dependsOn:
    - name: cert-manager
# values.yaml
  values:
    fullnameOverride: monitoring
    alertmanager:
      config:
        route:
          routes:
            - receiver: 'null'
              matchers:
                - alertname =~ "InfoInhibitor|Watchdog"
        receivers:
          - name: 'null'
        externalUrl: http://alertmanager.toliveistolearn.com/
    grafana:
      grafana.ini:
        server:
          root_url: http://grafana.toliveistolearn.com/
    kubernetesServiceMonitors:
      enabled: true
    kubeApiServer:
      enabled: true
    kubelet:
      enabled: true
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: true
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: true
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
    prometheusOperator:
      enabled: true
    prometheus:
      enabled: true
      prometheusSpec:
        externalUrl: https://prometheus.toliveistolearn.com/
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        podMonitorNamespaceSelector: {}
        podMonitorSelector: {}
        ruleNamespaceSelector: {}
        ruleSelector: {}
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 4Gi
{{- end }}