{{- if and .Values.argocd_ingress.enabled .Values.ingress_nginx.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-98"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default #infra
  source:
    repoURL: https://github.com/Societatea-Hermes/hermes-on-kubernetes.git
    targetRevision: main
    path: helmcharts/argocd-ingress
    helm:
      valueFiles: 
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end}}