{{- if .Values.monitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-97"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default #infra
  source:
    repoURL: https://github.com/Societatea-Hermes/hermes-on-kubernetes.git
    targetRevision: main
    path: helmcharts/monitoring
    helm:
      valueFiles: 
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end}}