apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-9998"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Societatea-Hermes/hermes-on-kubernetes-secrets.git
    targetRevision: main
    path: .
    helm:
      valueFiles: 
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true