apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hackathon-certificate
  namespace: apps
spec:
  secretName: tls-hackathon
  renewBefore: 360h0m0s # 15d
  dnsNames:
  - "hackathon.toliveistolearn.com"
  - "hackathon.societatea-hermes.ro"
  - "hackathon.societateahermes.ro"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer