apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
{{- end }}
{{- if .Values.cert-manager.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
{{- end }}
