apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-cariereinit-website
  namespace: production-apps
  labels:
    app.kubernetes.io/name: old-cariereinit-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: old-cariereinit-website
  template:
    metadata:
      labels:
        app.kubernetes.io/name: old-cariereinit-website
    spec:
      containers:
        - name: laravel
          image: ghcr.io/societatea-hermes/hermes-old-cariereinit-website:7
          ports:
            - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-hackathon-website
  namespace: production-apps
  labels:
    app.kubernetes.io/name: old-hackathon-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: old-hackathon-website
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: old-hackathon-website
    spec:
      containers:
        - name: laravel
          image: ghcr.io/societatea-hermes/hermes-old-hackathon-website:12
          ports:
            - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-ssmi-website
  namespace: production-apps
  labels:
    app.kubernetes.io/name: old-ssmi-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: old-ssmi-website
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: old-ssmi-website
    spec:
      containers:
        - name: laravel
          image: ghcr.io/societatea-hermes/hermes-old-ssmi-website:5
          ports:
            - containerPort: 8000