apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backups
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: pg-dump
            image: postgres:16.3-alpine
            imagePullPolicy: IfNotPresent
            args:
              - pg_dump
              - -Fc
              - -f
              - /backups/$(date +'%Y-%m-%d').dump
              - -h 
              - postgres.database.svc.cluster.local
            env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: POSTGRES_PASSWORD
              - name: PGUSER
                valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: POSTGRES_USER
            volumeMounts:
              - name: backup
                mountPath: /backups
          - name: rclone
            image: rclone/rclone
            imagePullPolicy: IfNotPresent
            args:
              - copy
              - /backups
              - gdrive:
              - --config
              - /config/rclone.conf
            volumeMounts:
              - name: rclone-config
                mountPath: /config
              - name: service-account
                mountPath: /data
              - name: backup
                mountPath: /backups
          containers:
            - name: done
              image: busybox
              imagePullPolicy: IfNotPresent
              command: ["echo"]
              args: ["Backup completed - $(date +'%Y-%m-%d')"]
          restartPolicy: OnFailure
          volumes:
            - name: rclone-config
              configMap:
                name: rclone-config
            - name: service-account
              secret:
                secretName: rclone-service-account-key
            - name: backup
              emptyDir: {}