apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    kubernetes.io/name: postgres
spec:
  serviceName: postgres
  selector:
    matchLabels:
      kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        kubernetes.io/name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.3-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-db
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 6Gi