kube-prometheus-stack:
  fullnameOverride: monitoring
  alertmanager:
    alertmanagerSpec:
      alertmanagerConfigMatcherStrategy:
        type: None
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            resources:
              requests:
                storage: 500Mi
  grafana:
    persistence:
      enabled: true
      storageClassName: "local-path"
      size: 1Gi
    grafana.ini:
      server:
        root_url: https://grafana.societatea-hermes.ro/
      users: 
        allow_sign_up: false
      auth:
        disable_login_form: true
      auth.proxy:
        enabled: true
        header_name: X-Auth-Request-Email
        header_property: email
        auto_sign_up: true
        headers: Name:X-Auth-Request-Preferred-Username Email:X-Auth-Request-Email Groups:X-Auth-Request-Groups Role:X-Auth-Request-Role
      security:
        disable_initial_admin_creation: true
        cookie_secure: true
  kubernetesServiceMonitors:
    enabled: true
  kubeApiServer:
    enabled: true
  kubelet:
    enabled: true
  kubeControllerManager:
    enabled: false
  coreDns:
    enabled: true
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: true
  prometheusOperator:
    enabled: true
  prometheus:
    enabled: true
    prometheusSpec:
      externalUrl: https://prometheus.societatea-hermes.ro/
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 4Gi