kube-prometheus-stack:
  fullnameOverride: monitoring
  alertmanager:
    alertmanagerSpec:
      alertmanagerConfigMatcherStrategy:
        type: None
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            resources:
              requests:
                storage: 500Mi
  grafana:
    persistence:
      enabled: true
      storageClassName: "local-path"
      size: 1Gi
    grafana.ini:
      server:
        root_url: http://grafana.societatea-hermes.ro/
      users: 
        allow_sign_up: false
      auth:
        disable_login_form: true
        oauth_auto_login: true
      auth.google:
        enabled: true
        allow_sign_up: false
        auto_login: true
        client_id: ${CLIENT_ID}
        client_secret: ${CLIENT_SECRET}
        scopes: openid email profile https://www.googleapis.com/auth/cloud-identity.groups.readonly
        auth_url: https://accounts.google.com/o/oauth2/v2/auth
        token_url: https://oauth2.googleapis.com/token
        api_url: https://openidconnect.googleapis.com/v1/userinfo
        allowed_domains: societatea-hermes.ro
        hosted_domain: societatea-hermes.ro
        use_pkce: true
      security:
        disable_initial_admin_creation: true
        cookie_secure: true
    envFromSecret: grafana-oidc
  kubernetesServiceMonitors:
    enabled: true
  kubeApiServer:
    enabled: true
  kubelet:
    enabled: true
  kubeControllerManager:
    enabled: false
  coreDns:
    enabled: true
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: true
  prometheusOperator:
    enabled: true
  prometheus:
    enabled: true
    prometheusSpec:
      externalUrl: https://prometheus.societatea-hermes.ro/
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 4Gi