kube-prometheus-stack:
  fullnameOverride: monitoring
  alertmanager:
  #add persistance to alertmanager
    config:
      route:
        routes:
          - receiver: 'null'
            matchers:
              - alertname =~ "InfoInhibitor|Watchdog"
      receivers:
        - name: 'null'
        - name: 'discord_alerts'
          webhook_configs:
            - send_resolved: true
              url_file: /etc/alertmanager/secrets/alertmanager-discord-webhook-url/webhook-url
      # externalUrl: https://alertmanager.societatea-hermes.ro/
    alertmanagerSpec:
      secrets: 
        - alertmanager-discord-webhook-url
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            resources:
              requests:
                storage: 500Mi
  grafana:
    grafana.ini:
      server:
        # root_url: http://grafana.toliveistolearn.com/
        # add persistance to grafana
  kubernetesServiceMonitors:
    enabled: true
  kubeApiServer:
    enabled: true
  kubelet:
    enabled: true
  kubeControllerManager:
    enabled: false
  coreDns:
    enabled: true
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: true
  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: true
  prometheusOperator:
    enabled: true
  prometheus:
    enabled: true
    prometheusSpec:
      externalUrl: https://prometheus.societatea-hermes.ro/
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 4Gi