apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: auth
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - secretName: tls-auth
  rules:
  - host: "auth.toliveistolearn.com"
    http:
      paths:
        - path: /oauth2
          pathType: ImplementationSpecific
          backend:
            service:
              name: oauth2-proxy
              port:
                number: 4180
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-errors
  namespace: auth
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      namespace: auth
      port: 4180
    query: "/oauth2/start"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  forwardAuth:
    address: http://oauth2-proxy.auth.svc:4180/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - Set-Cookie
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: auth
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app.kubernetes.io/name: oauth2-proxy
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-echo
  name: http-echo
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: http-echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: http-echo
  name: http-echo
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: http-echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-echo
    spec:
      containers:
      - image: mendhak/http-https-echo
        imagePullPolicy: Always
        name: http-echo
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: oauth2-proxy
  name: oauth2-proxy
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=google
        - --email-domain="societatea-hermes.ro"
        - --http-address=0.0.0.0:4180
        - --upstream=static://202
        - --scope=openid profile email
        - --redirect-url=https://auth.toliveistolearn.com/oauth2/callback
        - --whitelist-domain=.toliveistolearn.com
        - --pass-user-headers=true
        - --skip-provider-button=true
        - --set-authorization-header=true
        - --cookie-domain=.toliveistolearn.com
        - --set-xauthrequest=true
        - --reverse-proxy=true
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: OAUTH2_PROXY_CLIENT_ID
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: OAUTH2_PROXY_CLIENT_SECRET
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: OAUTH2_PROXY_COOKIE_SECRET
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP