apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-certificate
  namespace: monitoring
spec:
  secretName: tls-monitoring
  renewBefore: 360h0m0s # 15d
  dnsNames:
  - prometheus.toliveistolearn.com
  - alertmanager.toliveistolearn.com
  - grafana.toliveistolearn.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer