{{- if .Values.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - secretName: tls-monitoring
  rules:
  - host: prometheus.toliveistolearn.com
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: monitoring-prometheus
              port:
                number: 9090
  - host: alertmanager.toliveistolearn.com
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: monitoring-alertmanager
              port:
                number: 9093
  - host: grafana.toliveistolearn.com
    http:
      paths: 
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: monitoring-kube-prometheus-stack-grafana
              port:
                number: 80
{{- end }}
