apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    monitoring: prometheus
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    monitoring: prometheus
---
{{- end }}
{{- if .Values.certManager.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    monitoring: prometheus
---
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    monitoring: prometheus
---
